apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
  namespace: strimzi-operator
spec:
  name: strimzi-kafka-operator
  channel: stable
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic