production: false
proxy: edge

service:
  ports:
    http: 8080

postgresql:
  enabled: false

externalDatabase:
  host: kc-pg-postgresql
  port: 5432
  user: keycloak
  database: keycloak
  existingSecret: kc-pg-auth
  existingSecretPasswordKey: password

auth:
  adminUser: admin
  adminPassword: ""                 # оставляем пустым
  existingSecret: kc-admin-auth     # секрет с паролем
  passwordSecretKey: admin-password

extraVolumes:
  - name: realm-config
    configMap:
      name: kc-realm-app

extraVolumeMounts:
  - name: realm-config
    mountPath: /opt/bitnami/keycloak/data/import
    readOnly: true

extraEnvVars:
  - name: KEYCLOAK_IMPORT
    value: /opt/bitnami/keycloak/data/import/realm-export.json
  - name: KEYCLOAK_IMPORT_STRATEGY
    value: OVERWRITE_EXISTING      # или IGNORE_EXISTING todo: Разобраться почем уне идет полный импорт
  - name: KEYCLOAK_EXTRA_ARGS
    value: "--import-realm"
