apiVersion: v1
kind: Secret
metadata:
  name: kc-pg-auth
  namespace: jchat
type: Opaque
stringData:
  # superuser (root)
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "admin"

  # прикладная БД для keycloak
  POSTGRES_DB: "keycloak"
  USERDB_USER: "keycloak"
  USERDB_PASSWORD: "dev"
