apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: jchat
  labels:
    app: identity-service
spec:
  selector:
    app: identity-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8091