apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-broker
  namespace: jchat
  labels:
    strimzi.io/cluster: kafka
spec:
  replicas: 1
  roles:
    - broker
  storage:
    type: ephemeral